name: Deploy

on: "push"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          envkey_DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          envkey_DISCORD_MESSAGE_ID: ${{ secrets.DISCORD_MESSAGE_ID }}
          envkey_DISCORD_MUSIC_CHANNEL_ID: ${{ secrets.DISCORD_MUSIC_CHANNEL_ID }}
          envkey_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          envkey_SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          envkey_SPOTIFY_REDIRECT_URL: ${{ secrets.SPOTIFY_REDIRECT_URL }}

      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "whispering-harbor-22164"
          heroku_email: "maasch@rogers.com"
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs"
          env_file: ".env"
