name: Just deploy to heroku - test

on:
  push:
    branches:
      - pipeline-fix

jobs:

  deploy:
    runs-on: ubuntu-latest
   # needs: test
    environment: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
          justlogin: true
      - run: heroku container:login
      - run: heroku container:push -a $APP_NAME  web --arg COMMIT=$GITHUB_SHA
        env:
          APP_NAME: ${{secrets.HEROKU_APP_NAME}}

  docker:
    runs-on: ubuntu-latest
    environment: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
            COMMIT: $GITHUB_SHA
        with:
          context: .
          build-args:
            COMMIT
          push: true
          tags: marshallasch/botomir:latest
